### ISSUE TITLE
--allow-read is required even for scripts that don't touch the filesystem

### ISSUE THREAD

**Issue by doga** [andrewbrey/mdrb#1]
Hello Andrew,

Congrats, MDRB is a new idea that is working amazingly well. I am already using it for some of my GitHub repos.

One issue that seems a __security concern__ though:

The `--allow-read` option shouldn't be a requirement for running scripts that don't touch the filesystem.

For example, this works:

```shell
deno run \
   --allow-read --allow-run --allow-net --allow-env \
  https://deno.land/x/mdrb/mod.ts \
  https://raw.githubusercontent.com/doga/N3/main/README.md
```

but if I omit `--allow-read` as in here:

```shell
deno run \
   --allow-run --allow-net --allow-env \
  https://deno.land/x/mdrb/mod.ts \
  https://raw.githubusercontent.com/doga/N3/main/README.md
```

then this error occurs, although it shouldn't:

```text
┌ ⚠️  Deno requests read access to "/Users/da/Library/Application Support/dax".
├ Requested by `Deno.lstat()` API.
├ Run again with --allow-read to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all read permissions) >
```

Perhaps a new `mdrb` option for scripts that don't touch the filesystem could solve this. TIA.

**Comment by andrewbrey** [comment]
@doga I'm not sure that this is possible for two reasons:

1. By design, you can put whatever JS/TS code you want into your code blocks, so any permissions required to execute those blocks which aren't baked into your `mdrb` permission set at install time (see https://github.com/andrewbrey/mdrb?tab=readme-ov-file#installation) are going to be prompted.
2. For execution, this tool leverages [dax](https://deno.land/x/dax@0.39.2) which itself essentially requires `-A` permissions since it it can run arbitrary shell commands (and could thus be used to launch a Deno process with any permissions desired). Even if you don't use `--allow-read` in _your code blocks_, `mdrb` requires at least a handful of `--allow-read` permissions just to do its work (for instance, it will require reading the local file system to read any local **README.md** as well as read permissions to grab the wasm module for **dax**, and to read the path of the local **deno** binary exec path).

If it were possible to have different permissions per-module in Deno, then the path towards your feature request would be simpler, but for now (and most likely always) such a permissions model is not possible in Deno.

**Comment by doga** [comment]
Thanks for your fast reply (and for closing this issue).

As I see it, this security issue seems a showstopper for `mdrb` unless it is fixed. The owner of a Git repo will have no qualms about running `mdrb` against his/her own `README.md`, but he/she will think twice about running it against someone else's.

Again, great idea.

**Comment by andrewbrey** [comment]
@doga Thanks for the input and perspective - I do not believe this is a security issue, it's simply just a fact that a tool which has access to run arbitrary shell commands has broad privilege on the machine where it is running.

The feature afforded by Deno's permissions model is the fact that an end user can omit the permission flags in their invocation of `mdrb` and be _prompted_ for permissions at runtime at which time they can decide if they wish for execution to proceed. The runtime prompts and the cli permissions flags represent a tradeoff the user is empowered to make between convenience of it running without interruption (but with broader permissions granted ahead of time) and it running with more interruption (but with narrower/no permissions granted ahead of time).

Deno (and thus `mdrb`) allows the end user to decide on their own risk tolerance - a prompt for file system read permissions is not a security issue, it's a feature.

**Comment by doga** [comment]
About `dax`:

- `mdrb` could have 2 variants internally, one with `dax` enabled and one without it, and `mdrb` could use one or the other depending on an option (`--no-fs` or similar). This is an obvious one, but I am guessing you've already thought about it.

About the `--allow-read` option:

- Much too general. Would be more reasonable to enumerate the paths that really need to be read for a given `README.md`. What does `mdrb` really need to read? `deno` path? `dax` path in some cases? What else? No-holds-barred will be a no-go for many.
- `mdrb` does not need to be `deno install`ed, so the `--allow-read` option can be specified per-run.

The issue I've posted here is about `--allow-read`, but `--allow-env` is also a security concern. On a positive note I'll mention the fact that `mdrb` does not require `--allow-write` for all runs.

Again, great idea, and __making security a core feature__ would radically improve `mdrb`'s prospects, but I am sure you are aware of that. As for me, I'll keep on using `mdrb` in my READMEs.
